# Site settings
title: Notes for the future me
name: Yoriyasu Yano
email: yorinasub17@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notes.yano-san.com" # the base hostname & protocol for your site
github_username:  yorinasub17
linkedin_url: https://www.linkedin.com/pub/yoriyasu-yano/1b/72/903/


# Build settings
markdown: kramdown
permalink: pretty
pygments: true
